name: Build and push to ECR
# Trigger the workflow on push to the main branch
on:
 push:
   branches:
     - main
# Define the jobs
jobs:
 # Job to build and push the image
 build-and-push:
   # Run the job on an Ubuntu runner
   runs-on: ubuntu-latest
   # Set some environment variables
   env:
     # Name of the AWS region
     AWS_REGION: us-east-1
     # Name of the ECR repository
     ECR_REPOSITORY: my-app
     # Name of the image
     IMAGE_NAME: my-app
   # Steps of the job
   steps:
     # Checkout the code from the repository
     - name: Checkout code
       uses: actions/checkout@v2
     # Configure AWS credentials
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         # Use the AWS access key and secret key stored as secrets in the repository settings
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}
     # Login to ECR
     - name: Login to ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
     # Build the image
     - name: Build the image
       run: docker build -t $IMAGE_NAME .
     # Tag the image
     - name: Tag the image
       run: docker tag $IMAGE_NAME:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_NAME
     # Push the image to ECR
     - name: Push the image to ECR
       run: docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_NAME