name: Calculate Factorial

on:
  workflow_call:
    inputs:
      num:
        description: 'Enter Number'
        required: true
        type: number

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Python Script
        run: python factorial.py ${{ inputs.num }} 