name: Dispatch Workflow
on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First Number'
        required: true
        type: number
jobs:
  call-callable:
    uses: .github/workflows/callable.yml
    with:
      num: ${{ inputs.num }}